Detect File Change

* 概要
detfcはファイルやディレクトリの変化を検出するコマンドラインツールです。
変化を検出したら、記録ファイルを更新したり、任意のコマンドを実行したりします。

* コマンドライン

#+BEGIN_QUOTE
detfc [<option> | <target>]...
#+END_QUOTE

- /target/ :: チェック対象とするファイルまたはディレクトリです。
- /option/ ::
  - -db /DB filename/ :: 変化を調べるのに必要なデータを格納するファイルへのパスです。存在しない場合は新しく作成します。変化を検出したときのみ書き換えます。このオプションは必須です。
  - -r :: /target/ にディレクトリが指定されている場合、その子孫エントリを再帰的に調べてチェック対象に加えます。
  - -d :: ディレクトリ自身をチェック対象に加えます。ディレクトリの更新日時を考慮します。
  - -ext /suffix/ :: チェック対象とするファイルの接尾辞です。複数指定できます。指定しなかった場合は全てのファイルがチェック対象となります。
  - -e /command/ :: 変化を検出したときに実行するコマンドです。コマンドが0以外の終了ステータスで終了したとき、detfcは失敗の終了ステータスで即時終了します。そのとき、-bが指定されていない場合DBは更新されません。
  - -m /checking method name/ :: 変化検出アルゴリズムの名前です。デフォルトは2です。
  - -v :: 冗長なメッセージを出力します。変化を検出したときに何が変化したかを表示します。
  - -b :: 変化を検出したとき、-eで指定したコマンドを実行する前にDBファイルを書き出します(デフォルトは実行した後)。
  - -i :: -eで指定したコマンドが失敗しても処理を続行します。デフォルトはコマンドが失敗した段階でdetfcは失敗の終了ステータスで終了します(-bが指定されていない場合DBは更新されません)。
  - -nw :: DBファイルの書き出しを抑制します。-vと合わせることで変化しているかをメッセージで確認できます。

* 変化検出アルゴリズム
- 0 または fast :: DBファイルの更新日時より新しい更新日時を持つチェック対象が一つでもあるかどうかを調べます。
                   変化を検出した場合、DBファイルの更新日時を発見した日時へ更新します。
                   一つでも見つかったら処理を打ち切るため、最も高速です。
- 1 または dirsummary :: ディレクトリ毎にその直下にあるチェック対象の数、ファイルサイズの合計、最も新しいチェック対象の更新日時を求め、それが変化しているかを調べます。
     ただし、コマンドラインで直接指定したチェック対象(トップレベルターゲット)は、一つのディレクトリの下に存在するものとして扱います。
     変化を検出した場合、DBファイルには求めたディレクトリ毎の情報を書き出します。
- 2 または filestat :: チェック対象毎の更新日時、ファイルサイズ、ファイルタイプが変化しているか、また、以前存在していたチェック対象が無くなっているかどうか、また、以前存在しなかったチェック対象が存在するかどうかを調べます。
     変化を検出した場合、DBファイルには全チェック対象のファイル情報を出力します。

- (未対応) :: filestatに加え、ファイル内容のMD5を調べます。

| method | 速度 | DBファイル容量                       | 削除検出 | 追加検出       | 更新日時検出                                   | ファイルサイズ変化検出         | 名前の変化検出                         |
|--------+------+--------------------------------------+----------+----------------+------------------------------------------------+--------------------------------+----------------------------------------+
|      0 | 速   | なし(0)                              | できない | 更新日時による | DBファイルより新しい場合のみ検出               | しない                         | できない                               |
|      1 | 中   | 再帰的に検出したディレクトリ数に比例 | 不正確   | 不正確         | ディレクトリ毎の過去の最新と異なる場合のみ検出 | ディレクトリ毎の総サイズの一致 | 再帰的に検出したディレクトリのみできる |
|      2 | 遅   | チェック対象数に比例                 | 正確     | 正確           | チェック対象毎の不一致を検出                   | チェック対象ごとの一致         | できる                                 |

* 変化検出後のコマンド実行とDBファイル書き換えタイミングについて

detfcは変化を検出したとき次の処理を行います。

- -eコマンド実行 :: -eで指定されているコマンドを実行します。
                    コマンドが失敗の終了ステータスを返した場合、detfcも失敗の終了ステータスを返して即時終了します。
                    このとき、-bが指定されていない場合はDBファイルは書き換えられません(状況に変化が無ければ、次回も再度同じ変化を検出します)。
- DBファイル書き換え ::
  - -nwが指定されている場合は書き換えません。
  - -bが指定されている場合は-eコマンド実行の前に書き換えます。-eで指定されているコマンドが失敗しても確実に書き換えます。
